-- SOLUCIÓN DEFINITIVA: RECREAR TABLA COBRADORES
-- Ejecutar este script en Supabase SQL Editor para corregir el esquema corrupto

-- 1. Eliminar tabla corrupta (CUIDADO: Borra los datos de cobradores)
DROP TABLE IF EXISTS public.cobradores CASCADE;

-- 2. Recrear tabla cobradores con estructura correcta
CREATE TABLE public.cobradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT,
    zona_id BIGINT REFERENCES public.zonas(id),
    active BOOLEAN DEFAULT true,
    telefono TEXT,
    user_id UUID REFERENCES auth.users(id)
);

-- 3. Restaurar permisos
GRANT ALL ON TABLE public.cobradores TO postgres, anon, authenticated, service_role;

-- 4. Insertar cobrador de prueba inicial
INSERT INTO public.cobradores (nombre, email, zona_id, active, telefono)
SELECT 'Cobrador Prueba', 'cobrador.prueba@gmail.com', id, true, '0000000000'
FROM public.zonas
LIMIT 1;

-- 5. Forzar recarga de esquema
NOTIFY pgrst, 'reload config';
