-- Script completo de inicialización y reparación de base de datos
-- Ejecuta este script en el SQL Editor de Supabase para corregir errores de tablas faltantes

-- 1. Tabla Zonas (Requerida por Cobradores)
CREATE TABLE IF NOT EXISTS public.zonas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre TEXT NOT NULL
);

-- Insertar zonas por defecto si no existen
INSERT INTO public.zonas (nombre)
SELECT 'Zona Norte' WHERE NOT EXISTS (SELECT 1 FROM public.zonas);

INSERT INTO public.zonas (nombre)
SELECT 'Zona Sur' WHERE NOT EXISTS (SELECT 1 FROM public.zonas WHERE nombre = 'Zona Sur');

-- 2. Tabla Cobradores
CREATE TABLE IF NOT EXISTS public.cobradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT,
    zona_id BIGINT REFERENCES public.zonas(id),
    active BOOLEAN DEFAULT true,
    telefono TEXT,
    user_id UUID REFERENCES auth.users(id)
);

-- Asegurar que las columnas existan (por si la tabla ya existía pero incompleta)
ALTER TABLE public.cobradores ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE public.cobradores ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
ALTER TABLE public.cobradores ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
ALTER TABLE public.cobradores ADD COLUMN IF NOT EXISTS zona_id BIGINT REFERENCES public.zonas(id);

-- 3. Tabla Prestamistas (Administradores)
CREATE TABLE IF NOT EXISTS public.prestamistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT,
    telefono TEXT,
    user_id UUID REFERENCES auth.users(id)
);

-- Asegurar columnas en prestamistas
ALTER TABLE public.prestamistas ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE public.prestamistas ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- 4. Permisos básicos (necesario si RLS está activo o para roles anon/authenticated)
GRANT ALL ON TABLE public.zonas TO postgres;
GRANT ALL ON TABLE public.zonas TO anon;
GRANT ALL ON TABLE public.zonas TO authenticated;
GRANT ALL ON TABLE public.zonas TO service_role;

GRANT ALL ON TABLE public.cobradores TO postgres;
GRANT ALL ON TABLE public.cobradores TO anon;
GRANT ALL ON TABLE public.cobradores TO authenticated;
GRANT ALL ON TABLE public.cobradores TO service_role;

GRANT ALL ON TABLE public.prestamistas TO postgres;
GRANT ALL ON TABLE public.prestamistas TO anon;
GRANT ALL ON TABLE public.prestamistas TO authenticated;
GRANT ALL ON TABLE public.prestamistas TO service_role;

-- 5. Verificar estado final
SELECT 
    table_name, 
    count(*) as columns_count
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name IN ('cobradores', 'prestamistas', 'zonas')
GROUP BY table_name;
